### ISSUE TITLE
Turn on/off the led quickly, it stucks

### ISSUE THREAD

**Issue by billyjoker** [mcuhq/Android-Simple-Bluetooth-Example#2]
Hi, i've detected if i turn on and turn off very quickly, it stucks, so i have to reset the arduino to work well again. I do not know if it is limited by the baud rate or whatever. 

My scenario:  i'm testing sending/receiving a String (3 chars) with a timer task, sending from Android with a 100ms period. So, Arduino receive it correctly, on, off, on, off... but after some executions, arduino stucks, i think that the `bluetooth.available()` condition change its states.

I've tried with a `delay(5);` after each on/off, improving the test, but i get stuck again after some seconds working rightly.

I've tried to thange the baud rate from my initial 9600 to some other, but it fails, i can not get it work if i change the baud rate.

`bluetooth.begin(19200); //or some other standard speed rate, does not work anymore`

Any ideas? Thx!!

**Comment by billyjoker** [comment]
Hi, yesterday i've been testing with it and finally i figured out this rare problem. The problem was a method in my arduino code (inside the loop) defined as returning a String, so i redefined it as a void method and... voilá! The execution never stuck again.

Code that stucks in the loop (when reading data 100ms period): 

```
// btData is what i read well with bluetoot.read() (i've checked it hardly, no nulls, no parsing errors)
String send2Vibra(String btData){
  byte channel = (byte)btData.substring(0,1).toInt();
  byte velocity = (byte)btData.substring(1,btData.length()).toInt();
  ...
}
```


**Fixed code;**

```
void send2Vibra(String btData){
  byte channel = (byte)btData.substring(0,1).toInt();
  byte velocity = (byte)(btData.substring(1,btData.length())).toInt();
  ...
}
```

So this issue could be closed although i have yet to testing the change of the baudRate

**Comment by bauerjj** [comment]
ok, glad you got it working!
