### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by desuto** [mcuhq/Android-Simple-Bluetooth-Example#6]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by bauerjj** [comment]
Sure - sounds good!

**Comment by desuto** [comment]
I have designed the logo. What do you think ? do you like it ?
let me know if anyone wants to change.
![simpel bluetooth](https://user-images.githubusercontent.com/39637790/40624701-5697bec4-62d8-11e8-932d-042b95007e80.png)

**Comment by bauerjj** [comment]
Sweet! You can go ahead and add it to the icon image for the app and submit a pull request

**Comment by desuto** [comment]
I have upload all files to this link 
https://drive.google.com/open?id=1cttkBreFbUSsb7jhDKaR7j_5KwE0oAyS

And I have sent you pull requests. please check it.
